### ISSUE TITLE
How to support modern AWS credential management? (Request for comment)

### ISSUE THREAD

**Issue by danielcompton** [s3-wagon-private/s3-wagon-private#34]
AWS has a number of ways to provide credentials that s3-wagon-private doesn't really support. It would be good to integrate into that ecosystem. I think this should mostly be a matter of upgrading to the latest AWS SDK, but I'm not sure how tools like `aws-vault` should fit into this.

This issue is to get feedback from users in how and where they want to use this plugin, and what auth mechanisms should be supported.

The standard [hierarchy](http://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs) (see Reading Credentials at Run Time) is:
1. In environment variables.
2. In the central credentials file (~/.aws/credentials or %USERPROFILE%.aws\credentials).
3. In an existing default, SDK-specific configuration file, if one exists. This would be the case if you had been using the SDK before these changes were made.
4. For the .NET SDK, in the SDK Store, if it exists.
5. If the code is running on an EC2 instance, via an IAM role for Amazon EC2. In that case, the code gets temporary security credentials from the instance metadata service; the credentials have the permissions derived from the role that is associated with the instance.

**Comment by sheelc** [comment]
Just wanted to mention a few things I've come across:

1. The standard hierarchy listed above has gotten slightly more complicated with IAM role support for ECS. The normal EC2 IAM role support uses the instance metadata service to get the IAM role. Now, with an ECS task, there is a `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` env var set and the task can hit that endpoint which seems to resolve to the running ecs-agent and then the metadata service. This new step is documented in the hierarchy listed in the [DefaultAWSCredentialsProviderChain](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html).

1. I think from #32, since it uses the DefaultAWSCredentialsProviderChain, the following are supported: env vars, language specific settings (like Java system properties), credentials file, ECS env var, IAM role from the metadata service. It seems like this DefaultAWSCredentialsProviderChain is being kept up to date as new ways are formed to auth? It might be a fine long term solution.

1. For the STS credentials support and needing `AWS_SESSION_TOKEN`, it looks like the DefaultAWSCredentialsProviderChain [handles that as well](https://github.com/aws/aws-sdk-java/blob/a51792ec9d34263c12de5231131b42bd7dc544d9/aws-java-sdk-core/src/main/java/com/amazonaws/auth/EnvironmentVariableCredentialsProvider.java#L46:L62), although I've never tried it.

Maybe a lot of the various ways to auth are now being addressed?

**Comment by danielcompton** [comment]
Yeah, that all makes sense and using the DefaultAWSCredentialsProviderChain seems like a good long term solution. Where do you think the credentials provided in `project.clj` should go in the chain? I'm not quite sure where I see that fitting in.

**Comment by sheelc** [comment]
Yeah that's a good point. Right now the credentials in `project.clj` bypass the credential chain and forms an S3 client directly with those credentials. 

Is it necessary to even have these? It would of course be a breaking change, but it might be easier and more succinct to just say to authentication is done by normal AWS SDK auth. This strategy seems to be how libraries like amazonica [describes it](https://github.com/mcohen01/amazonica#authentication). It would have the added benefit of being less confusing than password/passphrase (from #31). Additionally, if the apps themselves are using AWS in some way then it avoids sometimes having to both set `AWS_ACCESS_KEY` as well as `LEIN_USERNAME`, which are often times the same value. 

I think the only thing lost by removing it is if you perhaps need a separate key/secret for running the app as opposed to pulling down private dependencies -- and you need them to be different at the same time (as opposed to build time for something like an uberjar vs runtime). I'm not sure if this is a big use case for people or not.

**Comment by danielcompton** [comment]
Currently there's a few ways people can authenticate:

* Bare keys
* Keys as arbitrary env vars
* Keys with GPG creds

We don't really want to encourage bare keys, and keys with arbitrary env vars could be substituted by letting users specify an AWS profile. I don't see a good way to do the GPG creds, except reading them and setting them as env vars in the lein process.

**Comment by sheelc** [comment]
Ah got it, I didn't see GPG creds in the code and forgot about them. It does look like the GPG creds remain a special case and since leiningen supports them as first-class citizens, shouldn't be removed. Reading them from the provided `authenticationInfo` and setting them in the env would work in the provider chain, but it doesn't seem worth the effort over the current `if` condition. (The conditional seems like it would be necessary regardless since they can be null).

I think the README can be simplified though to just address two options: GPG or anything in the AWS provider chain. The following seems no longer necessary:

```clojure
{:url "s3p://mybucket/releases/"
 :username :env/aws_access_key ;; gets environment variable AWS_ACCESS_KEY
 :passphrase :env/aws_secret_key}
```

could just be
```
{:url "s3p://mybucket/releases/"}
```

since the AWS default `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` work now.

The fact that :username :env and :passphrase :env work could just be a side effect of leiningen for backwards compatible users?

**Comment by danielcompton** [comment]
Yep, that seems sensible. Anyone setting specific env vars (that aren't `AWS_...`) is probably going to be ok with setting up AWS credentials (or will already have them setup). The one thing I would like to support is being able to specify a different profile than default. For example at our company, we all setup our AWS profiles with a specific name, so that if we do any personal stuff on the same computer, the default profile won't accidentally mess with company resources.

> The fact that :username :env and :passphrase :env work could just be a side effect of leiningen for backwards compatible users?

Not sure if I understand this, are you saying that this would effectively be a no-op?

**Comment by sheelc** [comment]
Sounds good, I'll send over a PR for an updated readme then.

For multiple profiles, I think you're talking about AWS profiles and not leiningen profiles, in which case they should work just fine with env vars now. The DefaultAWSCredentialsProviderChain (the new hero) includes the ProfileCredentialsProvider which reads either the `AWS_PROFILE` env var or the `aws.profile` Java system property (which could just be checked in to project.clj if desired since it's non-sensitive and would help ensure using the correct profile).

For the :username :env stuff I was specifically talking about this line in the readme:
To use the environment for credentials, include :username :env :passphrase :env instead of :creds :gpg and export LEIN_USERNAME and LEIN_PASSPHRASE environment variables.

I believe all that behavior continues to work so no one is broken with a new version. (I think we're on the same page here -- stop documenting `LEIN_PASSPHRASE`  but let it work for now).

**Comment by danielcompton** [comment]
I think we're pretty good now for this, by support AWS SDK provider chains. Thanks heaps for your work @sheelc!
