### ISSUE TITLE
Unable to deploy to s3 in cn-north-1

### ISSUE THREAD

**Issue by joelittlejohn** [s3-wagon-private/s3-wagon-private#39]
Hi, thanks for all your hard work on this plugin. It's been really useful for us.

I'm having trouble deploying artifacts using s3-wagon-private to any S3 bucket in the cn-north-1 region. I suspect this is related to request signing as cn-north-1 only supports the [signature v4 signing process](http://docs.aws.amazon.com/general/latest/gr/signature-version-4.html).

When I try `lein deploy`, I see the following error:

```
Could not transfer artifact myartifact:myartifact:jar:1.0.16 from/to releases 
(s3p://mybucket/releases/): The AWS Access Key Id you provided does not exist in our
records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId;
Request ID: 14856B606B12E5CD)
```

I'm using `[s3-wagon-private "1.3.0-alpha2"]` and my credentials are set as environment variables `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_DEFAULT_REGION`. My lein configuration looks like:

```clj
:deploy-repositories [["releases" {:url "s3p://mybucket/releases/"
                                   :no-auth true}]]
```

I can execute other operations using the AWS CLI, such as `aws s3api list-buckets` so I'm certain that the credentials are valid. I can also deploy successfully to eu-west-1 with this lein configuration (using different credentials of course).

I haven't yet worked out the exact cause of the problem here although as mentioned above it seems likely that this is related to the signing process. I tried updating the aws-sdk to 1.11.86 but this didn't fix the problem.

**Comment by danielcompton** [comment]
Can you check hardcoding username and passphrase to see if that works?

**Comment by joelittlejohn** [comment]
Sure. I also tried this with username and passphrase specified like:

```clj
{:url "s3p://mybucket/releases/"
 :username :env/AWS_ACCESS_KEY_ID
 :passphrase :env/AWS_SECRET_ACCESS_KEY}
```
and finally with the key and secret hard-coded like:

```clj
{:url "s3p://mybucket/releases/"
 :username "AKAI..."
 :passphrase "..."}
```

both of these produced the same error.

**Comment by danielcompton** [comment]
From memory, AWS China is a completely separate deployment of AWS, and it doesn't share any IAM data with the rest of the publicly accessible AWS regions. Are the AWS keys you're using specifically created for the China version of AWS?

If that's not the case, here's two debugging steps:

* Can you try the same tests against `ap-northwest-2`? I'm pretty sure that region also only support v4 signed requests.
* Are you able to [enable](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html) and share the (sanitised) logs that are generated when trying to use the plugin?

**Comment by joelittlejohn** [comment]
Interestingly, when I try this in ap-northwest-1 or eu-central-1, I see the following error;
```
'eu-central-1' is not a valid location constraint
```

which is obviously related to aws-maven and the constants here:

https://github.com/spring-projects/aws-maven/blob/ce6a4ffbd8a59029ebe147124ac2d7ff1a7afd18/src/main/java/org/springframework/build/aws/maven/Region.java

however with those regions, at least s3-wagon-private gets as far as getting the buckets location. With a cn-north-1 deployment:

1. s3-wagon-private doesn't get as far as retrieving the bucket's region, it fails to do this because of the auth error
1. `cn-north-1` is not present even in the latest aws-maven Region class, so even if s3-wagon-private had been able to get the region, the next step would have failed

This leads me to believe this has nothing to do with Signature V4. I wonder if there is some other unsafe part of the aws-maven code, e.g. asuming that the 'partition' is `aws` when for cn-north-1 it is actually `aws-cn`.

I'll try to capture some debug output. I think I'll add a pull request to spring-projects/aws-maven to include some of the latest regions as this is required, no matter what.

**Comment by joelittlejohn** [comment]
Okay, it looks like this may be a long way from working. spring-projects/aws-maven is basically a stagnant project. There are some issues and pull requests that relate to this (and similar) problems and a few forks that have attempted to fix the issues. Removing the dependency on aws-maven would be a good move :)

**Comment by joelittlejohn** [comment]
It's strange how the 'not a valid location constraint' only seems to affect the jar file, all the other files (.asc, .asc.md5, .asc.sha1, .pom, .pom.asc, .pom.asc.md5, .pom.asc.sha1, .pom.md5, .pom.sha1) are published successfully when I use a region like ap-northeast-2.

**Comment by joelittlejohn** [comment]
I've gotten to the bottom of this one and it's a reasonably simple fix.

This line causes a problem when deploying with China credentials to a China bucket:

https://github.com/s3-wagon-private/s3-wagon-private/blob/ddb5bcc834510edeb167682c004ed00325f9a9cd/src/main/java/org/springframework/build/aws/maven/PrivateS3Wagon.java#L105

because it's not possible to get bucket details or use China credentials before you set the endpoint. The endpoint must be set to `https://s3.cn-north-1.amazonaws.com.cn` and interacting with any other non-China endpoint using China IAM creds will fail.

I'm not familiar with how Leiningen activates wagon plugins to handle certain repo protocols. Is it possible to introduce an s3-wagon-private configuration into the project.clj and read this at some point during the wagon's initialization?

**Comment by joelittlejohn** [comment]
BTW, when I build a version of this plugin that set the China S3 endpoint (instead of attempting to discover the endpoint via the bucket details) I was able to successfully publish to a China bucket.

**Comment by danielcompton** [comment]
I can think of a few possibilities:

* Look for `AWS_DEFAULT_REGION` and use that to find the bucket details.
* Make the endpoint part of the lein config (either in the S3 URL, or as another key)
* Build a separate version of the plugin for China

I'm not so keen on the third one. It would be interesting to know what the AWS recommended way of doing this is, as I imagine the same issues would apply for govcloud or any other private AWS region.

Can you share a snippet of what you changed?

Looks like we should probably use something like this: https://aws.amazon.com/articles/3912

```java
AmazonEC2Client ec2 = new AmazonEC2Client(myCredentials);
ec2.setEndpoint("ec2.ap-southeast-1.amazonaws.com");
ec2.describeInstances();
```

https://github.com/elastic/elasticsearch-cloud-aws/commit/4c02a017b43539d26964b639a71bf589cba1f72c is slightly relevant

http://web.archive.org/web/20150322065533/http://docs.aws.amazon.com/general/latest/gr/isolated_regions.html

**Comment by sheelc** [comment]
@danielcompton @joelittlejohn Is it necessary to set the endpoint for China? I'm wondering if setting the region is sufficient. The China region is in the region enum of the SDK so perhaps when using this region the SDK takes care of the endpoint stuff for us?

Unfortunately I don't have any credentials to try this. @joelittlejohn do you know if it's possible to build an s3 client with credentials and the region without the endpoint? Or would you be able to try with your credentials?

If we can just set the region, here's another idea for the mix:

- The same way we started using the DefaultCredentialsProviderChain, we can use the AWS SDK [DefaultAwsRegionProviderChain](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/regions/DefaultAwsRegionProviderChain.html) which will look for `AWS_REGION` env var, region from the profile file, or from instance metadata. I haven't checked yet but we may already be using the default region provider chain. The only issue is for folks relying on this auto-region detecting feature that the wagon attempts to provide, which leads to the second piece.

- It looks like the SDK has a function for [getBucketLocation](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html#getBucketLocation-com.amazonaws.services.s3.model.GetBucketLocationRequest-) which can be translated to a region which can be set on the client. Since @joelittlejohn mentioned that we can't make any API calls to any endpoints outside of China with China IAM creds, we would have to make this auto-detect behavior fallback only so that the China region would succeed. (Alternatively, we could just leave the default aws-maven could for auto-detection in but it seems like that hard-coded list of regions will get out of date as compared to the SDK.)

**Comment by sheelc** [comment]
Excellent news @joelittlejohn! The only trickiness I can think of then is the DefaultAwsRegionProviderChain errors when it can't find a region so we'll just have to be careful of that to make sure we get to the fallback behavior.

I should be able to take a stab at implementing this over the weekend for review.
