### ISSUE TITLE
Deploy standalone build to s3 instead of standard build

### ISSUE THREAD

**Issue by Freezystem** [s3-wagon-private/s3-wagon-private#50]
Hi,

Is there an option or something I can do to send standalone version of my build to s3 instead of the regular one.
I need my project to embed all its dependencies as it contains local `.jar` file.

Regards.

**Comment by danielcompton** [comment]
@Freezystem are you talking about building an uberjar instead of a standard JAR? I don't think there is anything that S3-wagon-private would do that would make this any easier or harder than deploying to any other maven repo. I haven't used any of them, but one of these might be helpful?

* https://github.com/camechis/lein-deploy-uberjar
* https://github.com/BrightNorth/uberjar-deploy
* https://github.com/dmitrig01/lein-deploy-uberjar

**Comment by Freezystem** [comment]
Yes I'm building an uberjar but all dependencies seems to just be references that are downloaded later on. It works when I'm building my project in local but fails in my CI because the local jar builded as a maven package isn't available. I'll take a look at these libs thanks a lot.
