### ISSUE TITLE
Lein 2.8.0 breaks the AWS SDK provider class

### ISSUE THREAD

**Issue by nickmbailey** [s3-wagon-private/s3-wagon-private#51]
1.3.0 added support for using the aws sdk to load aws creds. In lein 2.7 you hit that path here:

https://github.com/s3-wagon-private/s3-wagon-private/blob/v1.3.0/src/main/java/org/springframework/build/aws/maven/PrivateS3Wagon.java#L98

This works because the auth info object is null and we hit that first if branch.

In lein 2.8.0 they added this:

https://github.com/technomancy/leiningen/blob/2.8.0/leiningen-core/src/leiningen/core/classpath.clj#L200

By setting private-key-file to an empty string in the default case, a null object will never be passed to the PrivateS3Wagon class and it's impossible to load credentials using the default provider class. Filing a ticket here although arguably the fix might belong in leiningen.

**Comment by danielcompton** [comment]
Ouch, I don't have time to work on this at the moment, but happy to take a PR.

**Comment by nickmbailey** [comment]
Added a pr:

https://github.com/s3-wagon-private/s3-wagon-private/pull/52

It's based off of v3.1.0 in case you want to cut a 3.1.1 (we're stuck on lein 2.7 until this gets fixed but not a huge deal) but it also merges cleanly with master.

I only did the empty string check for private key file since an empty string for a filename is definitely invalid and I wasn't sure of any weird edge cases around the other three accepting an empty string as a valid value. It fixes deploying with lein 2.8.0 in our case.

**Comment by sheelc** [comment]
The PR (#52) looks fine to me (commenting here to keep the discussion in one place) and helps to reconcile some of the mismatches that seems to have occurred.

Unfortunately, it looks like this has been quite the domino effect. It all starts with the aws-maven dependency (at the version we depend on) gets the AWS secret key from `passphrase`. Passphrase has, for a while, been intended only to be used for if there's a private-key-file (otherwise just password should be used for secret values). Because of this dependency on a fairly old version of aws-maven, s3-wagon-private has required users to specify passphrase. Aether has recently gotten more strict and doesn't pass `passphrase` through unless there is actually a private-key-file (which seems fair). To help s3-wagon-private, Leiningen did a quick patch for us by setting [private-key-file to empty string](https://github.com/technomancy/leiningen/blob/2.8.0/leiningen-core/src/leiningen/core/classpath.clj#L200) so that we could at least receive the creds based on aether being more stringent (and now the creds aren't null but an object that's all empty). 

Arguably, the bigger fix is as suggested in #47 that s3-wagon-private should only be using passphrase if there's a private key file and at all other times password. aws-maven has updated to use `getPassphrase` instead of `getPassword` in [this commit](https://github.com/spring-projects/aws-maven/commit/7a9b3d627bea2e226ea22e9665f86fa3272720c9). It seems to be that s3-wagon-private should move to the same password/passphrase semantics that everyone else has, but it is a breaking change. (One that I think is worth it because then both our and leiningen's shims can be removed.) @danielcompton any thoughts?

**Comment by danielcompton** [comment]
I agree @sheelc, this makes sense. It's a shame that it has to be a breaking change, but I think it's the best option we have here.

**Comment by joekiller** [comment]
Just wanted to throw this out. We use private maven repos and this plugin to retrieve them. Alongside we also use lein-npm ("0.6.0"). Our build runs:

```
lein npm install
lein test
...
```
and it seems that `lein npm install` silently gets our private maven artifacts via s3-wagon-private.

I'm unsure why as I haven't been able to dig but perhaps there is a workaround present there.

**Comment by danielcompton** [comment]
Fixed in #52.

**Comment by moea** [comment]
@joekiller n.b. `lein npm install` runs `lein deps`.

**Comment by joekiller** [comment]
@moea agreed. That's why it was perplexing that everything worked in that context.
